### ISSUE TITLE
Document file previews

### ISSUE THREAD

**Issue by Lampwick** [cerebroapp/cerebro#139]
It would be great if previews of documents in formats such as .doc .docx .xls .xlsx .odt .odp .ppt , etc. were included.

**Comment by KELiON** [comment]
@Lampwick I don't think it is possible. When I checked these formats I found [library](https://github.com/SheetJS/js-xlsx) for xls that can help, but nothing for docs. 

I see only one way of rendering doc and docx files that is sending them to web services, like google docs and get preview from them. But it is not a solution, because no one wants to send their private files to third-party services.

**Comment by maximbaz** [comment]
Just as an idea, there is [odt2txt](https://github.com/dstosberg/odt2txt) which could be leveraged if it is available on the user's computer, but of course it will not generate any nicely formatted preview, it will just retrieve the text.

**Comment by Lampwick** [comment]
It might be worth taking a look at the code for Sushi which acts like osx quicklook and generates previews for .doc, .xls, .ppt, .odt, .odp, etc.

**Comment by oguhpereira** [comment]
I believe this is a suggestion for a plugin not to follow natively in this repository. Since it doesn't make sense at the moment and it's too old I will close this issue.
