### ISSUE TITLE
gtk-primary-button-warps-slider error

### ISSUE THREAD

**Issue by killown** [cerebroapp/cerebro#152]
➜  ~ cerebro 
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x25200023ff20)" of type `gboolean'

gtk3 3.22.8-1 gtk2 2.24.31-1

**Comment by bil-elmoussaoui** [comment]
Has nothing to do with Cerebro as it's not a Gtk application. It's an issue with your .gtkrc file, if you change the gtk theme it will work without any issue.
Or at worst, wait until the next release of electron (will use the next version of chrome which uses Gtk3 instead of Gtk2 -> no more gtkrc files on gtk3)

**Comment by dubisdev** [comment]
I'm closing this as an old issue.

Try with 0.7.1, if the problem persists you can open a new issue
