### ISSUE TITLE
Feature Request: Toggle via commandline

### ISSUE THREAD

**Issue by pjz** [cerebroapp/cerebro#221]
I'd like a way to toggle cerebro on via the commandline, instead of via a hotkey.  The reason is that I use my window manager to do all my other keyboard remapping, and it would be nice to have it all in one place.  The idea is that calling a new command `cerebro-toggle` from the commandline would be the equivalent of hitting the hot-key.  Oh, and providing a way to disable the hotkey would be nice too. If running and in the tray it's still available via right-click, after all.

**Comment by KELiON** [comment]
@pjz what OS do you use? I'm not sure how to do it on Linux, but on Windows and Mac should work custom protocol. I.e. on mac you can use `open` command in terminal: `open cerebro://search`. You can even provide search term to it by `open "cerebro://search?term=hello"`

**Comment by pjz** [comment]
I'm on Linux.  And cerebro doesn't register itself as a protocol handler for `xdg-open` to use.

**Comment by infokiller** [comment]
This feature is very important to support some workflows, not just for centralizing keybinding definitions.
As an example, a user may want to trigger a sequence of events such as:
* Move to another virtual desktop
* Trigger Cerebro
* Modify the size of the Cerebro window

Is there any workaround for the current version to support such a workflow?

**Comment by maximbaz** [comment]
Since #235 is merged, starting `cerebro` a second time should just bring it on the screen.
To extend it with `toggle` functionality, I suggest just extending that bit, for example with something like that:

```
if (mainWindow.isMinimized()) mainWindow.restore()
else mainWindow.hide() <----------------------
```

Then it will be possible to externally bind a shortcut to run `cerebro` process.

**Comment by infokiller** [comment]
Thanks @maximbaz !
For my use cases starting it is enough (no need for the hiding of a toggle functionality).

**Comment by AXGKl** [comment]
Current appimage does not support starting a second time - and it would be anyway not exactly snappy for a launcher. So without a toggle possibility it looks like wayland users are out of luck ...
Maybe a  quick(?) workaround could be to add a local websocket listener on a unix domain socket file, which one could feed via any websocket client in order to be able to bind a wayland keyboard shortcut?

**Comment by AXGKl** [comment]
ok, I'm not a big javascripter but listening on a udp sock was simple enough for one massive hack getting cerebro working in gnome/wayland:

In the git version go to ` /app/main/createWindow.js`
```js
+ function listen_udp() {
+     const dgram = require('dgram');
+     const server = dgram.createSocket('udp4');
+
+     server.on('error', (err) => {
+           server.close();
+     });
+
+     server.on('message', (msg, rinfo) => {
+           toggleMainWindow()
+     });
+
+     server.on('listening', () => {
+           const address = server.address();
+           console.log(`server listening ${address.address}:${address.port}`);
+     });
+
+     server.bind(41234);
+ }
+    listen_udp()
``` 
so that you can toggle it via an `echo "a" > /dev/udp/127.0.0.1/41234` which you put into a script and bind that to the Ctrl-Space gnome hotkey.

**Comment by dubisdev** [comment]
I close this as moved to #500
