### ISSUE TITLE
[Discussion] Plugins API

### ISSUE THREAD

**Issue by KELiON** [cerebroapp/cerebro#280]
I'd like to discuss with plugins creators current plugins API. Do you think it is ok? Do you feel the lack of something? What would you change/add? What would you like to automate?

/cc @myslik @rafa-acioly @codingmatty @matmunn @JordanAdams @jsantiagoh @adrian011494 @Krbz @tiagoamaro @lubien @BrainMaestro @tenorz007 @ReeSilva @Kageetai @benoitzohar @glja021 @masterperas @adamclark64 @saleh7 @cades @tobico @hellocreep @klazutin @luisdavim @ocreaper @sibevin @fdivrp

**Comment by klazutin** [comment]
I was just going to say 'being able to store settings', but I see that has already been included in the latest release, so I'll go and check it out. 
Thanks for the great work!

**Comment by lubien** [comment]
One of the things that hit me right from the beginning was the lack of a standard Preview framework.

![image](https://cloud.githubusercontent.com/assets/9121359/24883250/82571202-1e1a-11e7-8bec-7f726227f324.png)

Here you can see the preview of the google search (core) plugin.

One of my first plugins was a MyAnimeList.net search plugin and I've wanted to do something like the google plugin but as soon as I realized that I'd need all boilerplating to create a pretty and working UI for the preview (with behind the scenes features like proper keybords interaction) I've dropped the idea and used just the display([xs]).

![image](https://cloud.githubusercontent.com/assets/9121359/24883371/fdbe02de-1e1a-11e7-8022-b39b6660dd0c.png)

My plugin works, but it differs from the core google preview. And even if I've made mine, maybe it'd be different looking from the overall cerebro layout.

I think this would be great if cerebro provided not an external library but a core library to display preview results. 

Why not external (like cerebro-plugin)? Because if it's core, cerebro could adapt it's design as much as cerebro changes itself.

**Comment by lubien** [comment]
Ps: by preview I don't mean just a list display, but could be useful displays for different common things like images, videos, file, table values, maybe charts idk, it should be discussed...

**Comment by luisdavim** [comment]
I agree with @lubien a standard preview framework would be great.

**Comment by codingmatty** [comment]
I agree, some React components that help with the preview would be awesome.

Also, I tried to look for documentation on "group plugins" and "plugin settings" but couldn't find anything.

**Comment by codingmatty** [comment]
i also want to point out this issue in cerebro-tools: https://github.com/KELiON/cerebro-tools/issues/1

**Comment by matmunn** [comment]
I used a modified version of the Preview react component bundled in the cerebro-gif plugin and that worked pretty well, so I don't have a problem with that.

The only problem I had was waiting until the user had stopped typing, since my plugin hits an API I didn't want it sending a request with every keystroke. I ended up using a pretty crude setTimeout setup to wait a set amount of time between keystrokes before sending the request.

**Comment by lubien** [comment]
Search for debouncing or throttling requests @matmunn

**Comment by matmunn** [comment]
@lubien I implemented a form of that already.

**Comment by lubien** [comment]
@matmunn nice

**Comment by BrainMaestro** [comment]
Yeah I think a standard preview framework with community styling is a good idea. Makes everything uniform and would speed up development. 

@matmunn instead of the setTimeout, you can use lodash debounce. I implemented something similar in the [weather plugin](https://github.com/BrainMaestro/cerebro-weather/blob/master/src/index.js), but you might need to tweak it a little.

**Comment by tiagoamaro** [comment]
Agreed with @lubien on deboucing/throttling. Depending on the API you're handling, it's not interesting to query for each letter the user is typing.

**Comment by rafa-acioly** [comment]
+1 on a default preview component.
@KELiON This would have prevented the error we encountered when I overwritten the default layout unintentionally.

**Comment by KELiON** [comment]
I see, that eeeeveryone is missing ui library! Lets move conversation about that to #282.

**Comment by Enzime** [comment]
Also I think we should potentially standardize some settings, like for example a `caseSensitive` setting for plugins that could have three options like `true`, `false`, `inherit` (which means it would get it from the global `caseSensitive` setting which can either be `true` or `false`)

**Comment by lubien** [comment]
With the new preview features in mind, I think we should discuss about the current keyword-based cerebro plugin scoping.

![image](https://cloud.githubusercontent.com/assets/9121359/24908946/71b01bf0-1e98-11e7-87b8-f90af837b576.png)

When I type any generic `foo` query I have two possibilities: google search or tranlations, two plugins with proper preview systems. So far so good.

![image](https://cloud.githubusercontent.com/assets/9121359/24909027/b9f6c616-1e98-11e7-82f5-3394ed1d62fe.png)

But to properly query plugins without proper preview I **must** use it's keyword. The reason is obvious. Without keyword scopping, every single query would hit all plugins who could hit lots of requests/renderings.

But as soon as everyone uses a preview system tha game changes! When I type `foo` I'd like to not only have the two possibilites (google or translation) but also any kind of plugin who could be useful for that question, my MyAnimeList search plugin or a NPM search plugin.

But as soon as the user had too much possibilites it would be hard to, after typing the query, go down until you find the plugin that you want to handle the current query.

**So here's my proposal:**

**1. Keywords are still valid scopping rules for plugins query.**

You can continue to type `npm (.*)` to search specificly on NPM.

**2. Users can select which plugins they want to use without the keyword.**

Suppose I do a lot of NPM searches and I don't like to start every query with `npm`.

As a user I can go to some settings on cerebro and select the NPM plugin as a plugin that could be used without keyword (just like google and translator). Now I can type `react` and a third option to search on NPM displays at cerebro.

**3. Plugins selected to be used without keyword could be prefixed with the keyword if wanted.**

Even after setting up the things of *2, users should be able to still query `npm react` and have it's responses.

**Comment by ReeSilva** [comment]
I'll go with a +1 on the Preview Framework. I believe that, for now, it's a must have. (and a lot of folks talking about the same is an evidence of this)

**Comment by codingmatty** [comment]
I agree with @lubien about configurable scoping. It could be as "simple" as allowing users to configure their own keywords for each plugin. i.e. configuring `npm ...` to  be `n ...`, or without the keyword altogether.
I personally would rather only allow google (and _maybe_ wikipedia) to be allowed for *all* queries. I have opted for the `Define` plugin over the `OSX Define` because of the scoping. It's faster for me to type a keyword than to scroll through all of the unrelated results list.

**Comment by Enzime** [comment]
My idea is to allow other plugins to extend each other, mainly the preview section.

I originally got the idea from seeing applications being listed but their preview just being some stats about the actual .desktop file, but I'm not sure this could be extended further than the new `basic-apps` plugin.

For example, Firefox and Chrome both have support for different profiles, and I would like the ability to select which one profile I'm launching from Cerebro, so if there were some way I could write a plugin to override the Firefox application's preview from `basic-apps`.

I realize this could be done by adding `NoDisplay=true` to the `firefox.application` and making a plugin that adds a new Firefox entry with the custom preview, but my main issue with this is that a lot of `.application` files are not modifiable without root, so if we could override these some way with a plugin that would be really good as it would let people drop in the plugin.

**Comment by dakaizou** [comment]
It'd be nice to have the ability to define (default) results priority.

**Comment by oguhpereira** [comment]
I will close this discussion issue so we can start using the new github discussion tool
