### ISSUE TITLE
Alternative search engines and translation services

### ISSUE THREAD

**Issue by captainhook** [cerebroapp/cerebro#32]
Although very useful built in features, it would be good to have a toggle to disable/enable the default search and translate plugins. Those concerned with privacy may not like use Google/Yandex.

 I will try to work on a duckduckgo search implementation.

**Comment by Phrohdoh** [comment]
@captainhook What is the status of a duckduckgo plugin?

**Comment by tiagoamaro** [comment]
@Phrohdoh @captainhook just published https://github.com/tiagoamaro/cerebro-duck-duck-go. There's no result preview yet, but it's a bare minimum to replace default Google's results (as it always stays on top of it).

**Comment by KELiON** [comment]
@tiagoamaro @Phrohdoh @captainhook awesome! I'm going to add settings for core plugins, so users could disable, i.e. google

**Comment by bobblkabb** [comment]
Would be a blessing to have an easy option to include search engines just with a link.
I use metager, startpage and unbubble for instance..

**Comment by 2br-2b** [comment]
I would love these as well! I use Brave Search. Due to the vast number of search engines, maybe there could be an option to add your own search engine?

**Comment by dubisdev** [comment]
Hi all!

> I would love these as well! I use Brave Search. Due to the vast number of search engines, maybe there could be an option to add your own search engine?

This would be easy if all search providers were returning the same API response when requesting suggestions, but they are not. Each JSON response is structured different so they can not be processed.

An alternative solution to this could be creating a plugin that offers two different features:

Set two plugin settings: `string` and `options` fields using the [plugins api](https://github.com/cerebroapp/cerebro/blob/master/docs/plugins/plugin-structure.md#settings).
1. If `string` field is empty, the plugin will use the selected engine in the `options` field. Providing suggestions and search functionality.
2. If `string` field is completed (with a search link like `https://search.brave.com/api/suggest?q=`) the plugin will use this to open the query, but won't be able to show suggestions.

By this way users whose engine is not listed can use their favourite engine. Meanwhile they can open an issue in the plugin repo so we know what engines are missing.

I'll start working on this soon.

**Comment by dubisdev** [comment]
Hi again!

`@cerebroapp/search` v1.0.0 has been released
https://github.com/cerebroapp/search/releases/tag/v1.0.0

This plugin includes support for Google, Brave, DuckDuckGo and Ecosia.
A custom search engine can be also added.

We have oppened a discussion there so anyone can comment what engines are missing.
https://github.com/cerebroapp/search/discussions/4

@oguhpereira we can close this issue

About translations: that issue is also related to an individual plugin and should not be here. If necessary, an issue can be oppened in one of these repos:
- https://github.com/cerebroapp/cerebro-skyeng
- https://github.com/cerebroapp/cerebro-yandex-translate
