### ISSUE TITLE
Minor layout issues / improvements

### ISSUE THREAD

**Issue by brpaz** [cerebroapp/cerebro#387]
- [ x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name* Linux mint 18.2 
- **Cerebro.app version**: 0.3.1

## Issue

Hello. 

### Subtitle position

Not sure if its the expected vehaviour but subtitle always appear at the right of the title, which look bad when you have a preview + subtitle.

See: ![](http://i.imgur.com/AWGlDxF.png)

Wouldnt make more sense to have the subtitle, below the title like this?

![](http://i.imgur.com/oH5842k.png)

### Autocomplete suggestions text color

With 0.3.1, it seems that the autocomplete suggestion text is now the same color as normal text of input. I think it looked better before. (only happens in light mode).

**Comment by niboan** [comment]
The same thing happened to me because I was running a devel version from source (with `yarn run dev`) on a config from an installed version. The chosen theme is configured with a relative path in `config.json`, and their working dir seems to be different. You will notice, that there is no theme selected in `config`.

As soon as you select a theme, it willl work in the devel version, but it will mess up the installed version (and vice versa).

**Comment by ThinkDigitalRepair** [comment]
It would be great as well if we had a way to back out of menus like settings and plugins. We have to close the window and then open again to do anything outside of that sub-menu

**Comment by rohmanhm** [comment]
Got same problem too. Ubuntu 16.04

**Comment by dubisdev** [comment]
I'm closing this issue as outdated. It seems to be fixed in the latest version.

Take a look at it and, if the problem persists, feel free to open a new issue.
