### ISSUE TITLE
Unable to run AppImage on Arch Linux

### ISSUE THREAD

**Issue by mckennajones** [cerebroapp/cerebro#58]
When running the AppImage on Arch Linux, after making it executable, I get the following error:

`/tmp/.mount_NUsefC/AppRun: line 77: 21426 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null`

This is using the latest release, 0.2.3.

**Comment by maximbaz** [comment]
Not saying that this shouldn't be investigated, but FYI, I'm running v0.2.3 just fine on my Arch.
All I did was to download the AppImage file and make it executable, like you did.

**Comment by maximbaz** [comment]
I've created AUR packages [cerebro](https://aur.archlinux.org/packages/cerebro) and [cerebro-git](https://aur.archlinux.org/packages/cerebro-git), that allow making a native build instead of using AppImage.

@mckennajones, @julianorafael try them out of you are interested.

**Comment by KELiON** [comment]
hey @maximbaz! I'm not good in linux apps distribution, so can you please explain a bit what is AUR package? Does it make sense to automate this process for each release?

**Comment by maximbaz** [comment]
AUR is a community-driven repository for people using Arch-based distros. 

The first script I created downloads *.tar.gz file from the Github releases page (the other one just clones `master` branch), then they install all necessary dependencies like `npm`, run all build commands like `npm install`, create binaries specific to the user's CPU architecture, place them in correct locations, create symlinks, put icons and license files in corresponding locations.

Basically every other user of Arch-based distro can now get the latest cerebro built specifically for their CPU architecture with one command. Same goes for updates, they will receive cerebro updates with the same approach as they receive system updates.

However the maintenance is required, not for the `cerebro-git` (that one just always takes `master` branch in whatever state it is), but for the `cerebro`, because there I hardcoded the latest release number.

It would be super-cool if we could somehow automate that. The package is a git repo, where with each release we need to update the version and sha256 sum of the *.tar.gz, run a command that generates some metadata, and do a git push. Can you think of a place where we could automatically execute this sequence of commands with every release?

**Comment by mckennajones** [comment]
@maximbaz Thanks so much. It works like a charm. I even learned a little bit about AUR packages from your previous post. Cheers!

**Comment by maximbaz** [comment]
I've scripted the upgrade procedure for the AUR package, it now requires running one command `./upgrade.sh 0.2.4` to push the update. 

@KELiON if you ever have an environment where you automatically build and deploy new releases, just ping me, I'll give you access and everything so that you can run this command there as well.

For now, anyone can use [this link](https://aur.archlinux.org/pkgbase/cerebro/flag/) to send me a notification that a new version is released, and I will run the upgrade command manually.

Perhaps it's worth mentioning in the README.md file about the existence of all community packages, so that people can find them easier.

As for this particular github issue, I think it is ready to be closed :)

**Comment by bil-elmoussaoui** [comment]
@KELiON Archlinux does have a docker image that can be used in order to automatically create an upgrade. 
This can be done using travis pretty easily i guess.

**Comment by oguhpereira** [comment]
The version used is too old, maybe try using the new version
