### ISSUE TITLE
Some plugins don't work

### ISSUE THREAD

**Issue by sgrontflix** [cerebroapp/cerebro#612]
Some plugins (like define or maps) don't work. When I type something like `define <word>` it shows `define` as a suggestion and then it completely disappears when I finish typing it. Same goes for maps, translate or any other plugin that requires a "side window".

I'm on Windows 10 and using version 0.8.0

**Comment by dubisdev** [comment]
Hi @sgrontflix
The both plugins you talk about are very outdated as their original authors are not maintaining them anymore. Normally they fail not as a Cerebro error but as an API error

![image](https://user-images.githubusercontent.com/77246331/191938835-79976fa3-e07a-46d0-bb65-7430e3c7875c.png)

As you see, define is trying to access a url but the server returns a 404.

That's because they haven't been updated and they don't work, but this is not a core error of the app.

Feel free to open a new issue in their corresponding repos:
- https://github.com/glja021/cerebro-define
- https://github.com/cerebroapp/cerebro-google-maps

**Comment by dubisdev** [comment]
You can test that other plugins like `cerebro-todoist` or `cerebro-google` work well and use the side window.

**Comment by dubisdev** [comment]
I'm closing this as it is out of the scope of this repo
