### ISSUE TITLE
[Discussion] Is this project abandoned already?

### ISSUE THREAD

**Issue by ZeroCommits** [cerebroapp/cerebro#666]

**Comment by dubisdev** [comment]
Hello everyone! As a contributor to the project, I decided to create a fork because there were many restrictions on contributing.

For those interested, here is a repository with a more polished and updated version of project. I'm not working now on It, but it is faster and uses more up-to-date dependencies.

https://github.com/RokiiApp

BTW PRs are welcome :)

**Comment by oguhpereira** [comment]
This is an old project with few developers maintaining it, without financial support. Due to this, our attention is a little smaller, but as much as possible we try to respond to some requests.

**Comment by xaocon** [comment]
@oguhpereira, thanks for the work you and team are doing. If someone was interested in helping, what would be most useful?

**Comment by oguhpereira** [comment]
There are several ways we need help:
- Test the product and report bugs and improvements (this is very important)
- Plugin creators and maintainers promote and keep the plugin active.
- Help with the core part of the project, raising pr's to fix bugs or helping with feature development.

One consideration about this is that there are usually some issues that we have flagged that we need help with.

**Comment by oguhpereira** [comment]
I will close this threed, at any point I will just open it again.
